.PHONY: clean clean-all clean-pycache clean-build

# remove Python caches only
clean: clean-pycache clean-build
	@echo "✅ Cleaned caches & build artifacts."

# remove EVERYTHING generated by runs/pipelines (be careful!)
clean-all: clean
	@python - <<'PY'
from pathlib import Path
import shutil
for p in [Path("runs"), Path("data/processed"), Path(".pytest_cache"), Path(".mypy_cache")]:
    if p.exists():
        shutil.rmtree(p, ignore_errors=True)
print("⚠️ Removed runs/ and data/processed/ (irreversible).")
PY

clean-pycache:
	@python - <<'PY'
from pathlib import Path
import shutil
# __pycache__ and *.py[co]
for p in Path(".").rglob("__pycache__"):
    shutil.rmtree(p, ignore_errors=True)
for ext in (".pyc", ".pyo"):
    for f in Path(".").rglob(f"*{ext}"):
        f.unlink(missing_ok=True)
print("🧹 Removed __pycache__/ and *.py[co].")
PY

clean-build:
	@python - <<'PY'
from pathlib import Path
import shutil
for p in [Path("build"), Path("dist")]:
    if p.exists():
        shutil.rmtree(p, ignore_errors=True)
for egg in Path(".").rglob("*.egg-info"):
    shutil.rmtree(egg, ignore_errors=True)
print("🧱 Removed build/ dist/ *.egg-info")
PY
