# conf/engine_backtest.yaml
mode: "multi"                           # or "single"
data_path: "runs/my_model/panel.parquet"  # columns: timestamp, symbol, close, signal
out_path: "runs/my_model/backtest.parquet"
price_col: "close"
signal_col: "signal"
engine:
  fee_bps: 1.0
  slippage_bps: 1.0
  latency_bars: 1
  target_vol_ann: 0.20
  max_leverage: 3.0
  vol_lookback: 60
