# Optional: point to a specific model; omit to auto-load latest
# model_path: models/price_predictor_2025-10-20_111841.pkl

# Raw data to build features from
data_path: data/latest_raw.csv

# (optional) runtime knobs
logging:
  log_path: logs/inference_log.jsonl
  explain: true   # set false in CI to skip SHAP
